### ISSUE TITLE
more descriptive attribute names

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#21]
[These](https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/values.yaml#L12-L64) top-level attributes should have more descriptive names and/or be grouped together by function:

```yaml
wallet_key_name: x
wallet_key_password: y
akash_chain_id: z
akash_node: a
```

or

```yaml
akash:
  key_name: x
  key_password: y
  chain_id: z
  node: a
```

For a couple of reasons:

1. logically grouping related attributes together makes reading configuration easier.
2. short top-level symbols can easily collide with other symbols (`key`, `from`, etc... are getting very close to default template functions)
