### ISSUE TITLE
Introduce Ephemeral Storage Requests and Limits for Akash-node Helm Chart

### ISSUE THREAD

**Issue by ghost** [akash-network/helm-charts#294]
We've observed that `akash-node` can consume significant disk space over time, potentially leading to storage issues. To address this and prevent future occurrences, we propose introducing Kubernetes `requests` and `limits` for ephemeral storage in the Akash-node Helm chart. This would allow the node to be restarted automatically when it reaches the specified storage limits, improving resource management and stability.

Suggested configuration:

```yaml
resources:
  requests:
    ephemeral-storage: "10Gi"  # Request 10 GiB of ephemeral storage
  limits:
    ephemeral-storage: "50Gi"  # Set a hard limit of 50 GiB of ephemeral storage
```

And these parameters should be configurable via the `values.yaml`.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

**Rationale:**

This configuration will ensure better control over disk usage by setting an initial request for storage and a hard limit to avoid excessive consumption. If the limit is reached, Kubernetes will automatically handle the pod lifecycle, preventing long-term storage issues. I.e. it'll simply bounce the pod and the node will quickly sync-up again.

Implementing this change will enhance overall reliability and resource management for Akash-node deployments.
